In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 32)
print(arr)
print(len(arr))
print(type(arr)) # <class 'numpy.ndarray'>
print(arr.shape) # shape: numpy 배열의 구조를 얻어온다.

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]
32
<class 'numpy.ndarray'>
(32,)


In [3]:
# reshape() 메소드는 numpy 배열의 차원을 변경한다. => 전체 데이터 개수는 같아야 한다.
v = arr.reshape(4, 2, 4)
print(v)
print(v.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]]]
(4, 2, 4)


<img src="./numpyImage/shape1.png" width="600" align="left"/>

<img src="./numpyImage/shape2.png" width="600" align="left"/>

numpy의 sum() 메소드 작동 방식

In [4]:
# sum() 메소드의 axis 속성의 기본값은 None이고 axis는 대상 차원보다 작은 값을 설정한다.
# 위의 예제에서는 데이터의 차원이 3이기 때문에 axis 속성은 2까지 지정할 수 있다.
print(v.ndim) # ndim: numpy 배열의 차원(Dimension)을 얻어온다.

3


In [5]:
# axis=None
# axis를 기본값으로 실행하면 대상 데이터의 모든 요소의 합계를 리턴한다. 면, 행, 열을 구분하지 않고 전체 합계를 계산한다.
# 대상 데이터에 포함된 모든 요소를 단순히 합산하는 연산이 실행된다.
print(v.shape)
print(v.sum()) # print(v.sum(axis=None))와 같은 표현이다.
print(v.sum(axis=None))

(4, 2, 4)
496
496


In [6]:
# axis=0
# axis=0는 x축을 기준으로 계산한 합계를 리턴한다.
# shape이 (4, 2, 4)인 데이터를 x축을 기준을 계산한 결과 shape은 면이 제거되고 (2, 4)이 리턴된다.
res = v.sum(axis=0)
print(res.shape)
print(res.ndim)
print(res)

(2, 4)
2
[[48 52 56 60]
 [64 68 72 76]]


axis=0은 가장 외곽의 괄호를 제거하는 이미지를 생각하면 된다.  
아래 그림처럼 가장 외곽의 괄호를 제거하고 각 행의 데이터는 위치별로 합계를 계산한다.  
<img src="./numpyImage/shape3.png" width="1000" align="left"/>

<img src="./numpyImage/shape4.png" width="600" align="left"/>

In [7]:
# axis=1
# axis=1는 y축을 기준으로 계산한 합계를 리턴한다.
# shape이 (4, 2, 4)인 데이터를 y축을 기준을 계산한 결과 shape은 행이 제거되고 (4, 4)이 리턴된다.
res = v.sum(axis=1)
print(res.shape)
print(res.ndim)
print(res)

(4, 4)
2
[[ 4  6  8 10]
 [20 22 24 26]
 [36 38 40 42]
 [52 54 56 58]]


axis=1은 가운데 괄호를 제거하는 이미지를 생각하면 된다.  
아래 그림처럼 가운데 괄호를 제거하고 각 행의 데이터는 위치별로 합계를 계산한다.  
<img src="./numpyImage/shape5.png" width="1000" align="left"/>

<img src="./numpyImage/shape6.png" width="600" align="left"/>

In [8]:
# axis=2
# axis=2는 z축을 기준으로 계산한 합계를 리턴한다.
# shape이 (4, 2, 4)인 데이터를 y축을 기준을 계산한 결과 shape은 열이 제거되고 (4, 2)이 리턴된다.
res = v.sum(axis=2)
print(res.shape)
print(res.ndim)
print(res)

(4, 2)
2
[[  6  22]
 [ 38  54]
 [ 70  86]
 [102 118]]


axis=2은 가장 안쪽 괄호를 제거하는 이미지를 생각하면 된다.  
아래 그림처럼 가운데 괄호를 제거하고 각 행의 데이터는 위치별로 합계를 계산한다.  
<img src="./numpyImage/shape7.png" width="1000" align="left"/>

<img src="./numpyImage/shape8.png" width="600" align="left"/>