In [1]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np

def pprint(arr):
    print('type: {}'.format(type(arr)))
    print('shape: {}, dimension: {}, dtype: {}'.format(arr.shape, arr.ndim, arr.dtype))
    print('numpy 배열의 데이터\n', arr, sep='')

numpy 파일 입출력

In [2]:
# numpy는 배열 객체를 바이너리(2진) 파일 또는 텍스트 파일에 저장하고 로딩하는 기능을 제공한다.
# 메소드 이름     기능                                                 파일 포맷
# np.save()       numpy 배열 객체 1개를 파일로 저장한다.               바이너리
# np.savez()      numpy 배열 객체 여러 개를 파일로 저장한다.           바이너리
# np.load()       numpy 배열 저장 파일로 부터 배열 객체를 읽어온다.    바이너리
# ============================================================================================
# np.savetxt()    numpy 배열 객체 텍스트 파일로 저장한다.              텍스트
# np.loadtxt()    텍스트 파일에 저장된 numpy 배열 객체를 읽어온다.     텍스트

In [3]:
a = np.random.randint(0, 10, (2, 3))
pprint(a)
b = np.random.randint(0, 10, (2, 3))
pprint(b)

type: <class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype: int32
numpy 배열의 데이터
[[6 9 9]
 [5 6 9]]
type: <class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype: int32
numpy 배열의 데이터
[[7 4 3]
 [7 6 5]]


In [4]:
# numpy 배열 객체를 바이너리 파일로 저장
# np.save(), np.savez() 메소드를 이용해서 배열 객체를 바이너리(2진) 형태의 파일로 저장할 수 있다.
# np.save(): 배열 1개를 저장한다. 확장자 => npy
# np.savez(): 배열 여러 개를 저장한다. 확장자 => npz

# a 배열을 바이너리 파일로 저장한다.
# np.save('경로명', 배열명)
np.save('./output/my_array1', a)
# a, b 배열을 바이너리 파일로 저장한다.
# np.savez('경로명', 배열명1, 배열명2, ...)
np.savez('./output/my_array2', a, b)

In [5]:
# np.load() 메소드로 npy, npz 파일로 부터 배열 데이터를 읽어올 수 있다.
# npy 파일 읽기
print(np.load('./output/my_array1.npy'))

[[6 9 9]
 [5 6 9]]


In [6]:
# npz 파일 읽기
print(np.load('./output/my_array2.npz'))
npzFiles = np.load('./output/my_array2.npz')
print(npzFiles['arr_0'])
print(npzFiles['arr_1'])

[[6 9 9]
 [5 6 9]]
[[7 4 3]
 [7 6 5]]


In [7]:
c = np.random.random((3, 4))
pprint(c)

type: <class 'numpy.ndarray'>
shape: (3, 4), dimension: 2, dtype: float64
numpy 배열의 데이터
[[0.91865957 0.0643028  0.31455548 0.25321714]
 [0.74493157 0.10290226 0.82600377 0.47987051]
 [0.18406685 0.51394959 0.93615522 0.44681719]]


In [8]:
# numpy 배열 객체를 텍스트 파일로 저장
# 텍스트 파일은 txt 파일의 의미하는 것이 아니고 csv 또는 tsv 파일을 의미한다.
# np.savetxt() 메소드로 배열 객체를 텍스트 파일 형태로 저장시킬 수 있다.
# np.savetxt('경로명', 배열명, delimiter='구분자')
np.savetxt('./output/saved.csv', c, delimiter=',') # csv 파일은 데이터를 ','로 구분한다.
np.savetxt('./output/saved2.tsv', c, delimiter='\t') # tsv 파일은 데이터를 tab으로 구분한다.

In [20]:
# np.loadtxt() 메소드로 배열 객체를 텍스트 파일 형태로 저장시킬 수 있다.
# np.loadtxt('경로명', dtype, delimiter='구분자')
saved = np.loadtxt('./output/saved.csv', dtype=np.float, delimiter=',')
pprint(saved)
print(np.loadtxt('./output/saved2.tsv', dtype=float, delimiter='\t'))

type: <class 'numpy.ndarray'>
shape: (3, 4), dimension: 2, dtype: float64
numpy 배열의 데이터
[[0.91865957 0.0643028  0.31455548 0.25321714]
 [0.74493157 0.10290226 0.82600377 0.47987051]
 [0.18406685 0.51394959 0.93615522 0.44681719]]
[[0.91865957 0.0643028  0.31455548 0.25321714]
 [0.74493157 0.10290226 0.82600377 0.47987051]
 [0.18406685 0.51394959 0.93615522 0.44681719]]


배열(행렬) 연산 - 산술 연산

In [23]:
a = np.arange(1, 10).reshape(3, 3)
pprint(a)
b = np.arange(9, 0, -1).reshape(3, 3)
pprint(b)

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열의 데이터
[[1 2 3]
 [4 5 6]
 [7 8 9]]
type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열의 데이터
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [25]:
# 덧셈: +, np.add()
print(a + b)
print(np.add(a, b))

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [26]:
# 뺄셈: -, np.subtract()
print(a - b)
print(np.subtract(a, b))

[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [27]:
# 곱셈: *, np.multiply()
print(a * b)
print(np.multiply(a, b))

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [29]:
# 나눗셈: /, np.divide()
print(a / b)
print(np.divide(a, b))

[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [30]:
print(np.exp(a)) # 지수

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [31]:
print(np.sqrt(a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [33]:
# 삼각함수
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


In [34]:
print(np.log(a)) # 로그

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]


In [36]:
print(np.dot(a, b)) # 행렬의 내적

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


<img src="./dot.png" width="1000" align="left"/>

배열(행렬) 연산 - 비교 연산

In [37]:
# 배열 요소별 비교: >, >=, <, <=, ==, !=
print(a == b)

[[False False False]
 [False  True False]
 [False False False]]


In [38]:
# np.array_equal() 메소드를 사용하면 배열 전체를 비교할 수 있다.
print(np.array_equal(a, b))

False


집계 함수  
numpy의 모든 집계 함수는 axis를 기준으로 계산하며 집계 함수에 axis를 지정하지 않으면 axis=None이 기본값으로 사용된다.

In [39]:
a = np.arange(1, 10).reshape(3, 3)
pprint(a)

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype: int32
numpy 배열의 데이터
[[1 2 3]
 [4 5 6]
 [7 8 9]]


합계: 배열.sum(), np.sum(배열)

In [43]:
# axis=None
# axis=None은 전체 배열을 행과 열을 구분하지 않고 전체 합계를 계산한다. 생략시 기본값으로 사용된다.
print(a.sum())
print(a.sum(axis=None))
print(np.sum(a))
print(np.sum(a, axis=None))

45
45
45
45


<img src="./numpyImage/numpyImage02.jpg" width="250" align="left"/>

In [45]:
# axis=0
# axis=0은 행을 기준으로 각 행의 동일한 인덱스 요소를 그룹으로 연산한다. => 각 열의 합계
print(a.sum(axis=0))
print(np.sum(a, axis=0))

[12 15 18]
[12 15 18]


<img src="./numpyImage/numpyImage03.jpg" width="250" align="left"/>

In [46]:
# axis=1
# axis=1은 열을 기준으로 각 열의 동일한 인덱스 요소를 그룹으로 연산한다. => 각 행의 합계
print(a.sum(axis=1))
print(np.sum(a, axis=1))

[ 6 15 24]
[ 6 15 24]


<img src="./numpyImage/numpyImage04.jpg" width="250" align="left"/>